version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout

      - run:
          name: Build and Test
          command: mvn -B verify
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

  release:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: |
          if [[ "$CIRCLE_TAG" != "" ]]; then
            VERSION="$(echo "$CIRCLE_TAG" | grep -Po '(?<=v).*')"
            mvn versions:set -DnewVersion=${VERSION} versions:commit
          fi
      - run:
          name: Build and Test
          command: mvn -s .circleci/settings.xml -B deploy -DskipTests

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
            requires:
              - build
            filters:
              tags:
                only: /^v.*/
              branches:
                ignore: /.*/